### ISSUE TITLE
Wrong month values for CRSP dummy data

### ISSUE THREAD

**Issue by mathisdrn** [tidy-finance/website#101]
Replicating [Accessing and Managing Financial Data](https://www.tidy-finance.org/python/accessing-and-managing-financial-data.html) and [WRDS **Dummy** Data](https://www.tidy-finance.org/python/wrds-dummy-data.html) to apply [Parametric Portfolio Policies](https://www.tidy-finance.org/python/parametric-portfolio-policies.html) creates an error when computing `evaluate_portfolio(weights_crsp)`. 

In evaluate_portfolio() at `evaluation_capm` line : 
ValueError: zero-size array to reduction operation maximum which has no identity

It likely comes from a mis-alignement of date between evaluation and factors_ff_monthly.
- evaluation['month'] is End of Month
- factors_ff_monthly['month] is Start of month
Which leads `evaluation.merge(factors_ff_monthly, how="left", on="month")` to not have any common `month` with `factors_ff_monthly`.

`evaluation` is constructed from `crsp_monthly` which I created following [WRDS **Dummy** Data](https://www.tidy-finance.org/python/wrds-dummy-data.html).

From WRDS Dummy Data : 
```  python
crsp_monthly_dummy = (stock_panel_monthly
  .assign(
    date=lambda x: x["month"]+pd.offsets.MonthEnd(-1),
    ret=lambda x: np.fmax(np.random.normal(size=len(x)), -1),
```

I am unsure at this point but it may be x["month"]+pd.offsets.MonthEnd(-1) who is incorrect here.
I don't have access to WRDS data to compare with dummy data.

Pandas version : 2.2.2
Database : running fine
Full replicate, no change to code, only diff is freshly installed environment.

**Comment by voigtstefan** [comment]
Changed the issue title from "[BUG] Parametric Portfolio Policies" to "Read in dummy dataset with pandas compromises date column "

**Comment by mathisdrn** [comment]
Hi @voigtstefan, 
I don't think the issue comes from reading the `.sqlite` file. 
`month` column is identical across notebooks generating dummy data, my sqlite file and reading them in parametric portfolio policies. 
Parametric portfolio policies runs without error by adding :
`crsp_monthly['month'] = crsp_monthly['month'] + pd.DateOffset(days=1)`.

I am not sure if this is fully reproducible but here my values : 
- `np.random.seed(1234)`
- numpy version : 1.26.4
- `start_date = pd.Timestamp("1960-01-01")` for both dummy and real data
- `end_date = pd.Timestamp("2022-12-31")` for both dummy and real data

Output :
<img width="428" alt="Capture d’écran 2024-04-15 à 12 08 22" src="https://github.com/tidy-finance/website/assets/116900975/8f3121c4-f054-4725-a5f9-2fc7cd85b384">
<img width="342" alt="Capture d’écran 2024-04-15 à 12 08 30" src="https://github.com/tidy-finance/website/assets/116900975/ad3acb0c-28f8-487b-9251-85a99c5652dd">

**Comment by christophscheuch** [comment]
I agree with @mathisdrn about the problem and the solution, but will confirm again on Wednesday. 

@voigtstefan you shouldn't read the R dummy data with pandas because R stores integers since 1970 and in the Python version we store strings. In an early version of TFWP we had integer conversion from the R database to the correct date in Python, but omitted it because we didn't want to support cross-language operations at the time.

The blog post you might refer to is this one (I'm not aware of anything else related): https://blog.tidy-intelligence.com/posts/data-storage-comparison/

**Comment by voigtstefan** [comment]
True, my apologies. I completely misread the prerequisites you described!

**Comment by christophscheuch** [comment]
Indeed `crsp_monthly["month"]` and `factors_ff_monthly["month"]` should be beginning of month, but `dummy_months` is end of month. So the most simple fix is to have 
```
dummy_months = pd.date_range(start_date, end_date, freq="MS") 
```
instead of `pd.date_range(start_date, end_date, freq="MS")`
