### ISSUE TITLE
Add reference to `tidyfinance` package to TFWR

### ISSUE THREAD

**Issue by christophscheuch** [tidy-finance/website#109]
Add it to preface or getting started?

**Comment by patrick-weiss** [comment]
I suggest a separate section in "getting started" -> "R package: TidyFinance".

Should we also include some references in the relevant sections (e.g., this download can also be achieved by using "function()")?

**Comment by christophscheuch** [comment]
So the proposal is: 
1. Add subsection to Getting Started about tidyfinance package and how to install
2. Add in-line mentions of tidyfinance functions

What do you think @voigtstefan and @dsforecast?

**Comment by voigtstefan** [comment]
Sounds good.
