### ISSUE TITLE
Change all `month` columns to `date`

### ISSUE THREAD

**Issue by christophscheuch** [tidy-finance/website#115]
The issue came up with `r-tidyfinance`: All `month` columns are actually dates and the frequency is in the object name anyway, e.g., `crps_monthly` vs `crsp_daily`. For month, one would typically expect the number of the month or the month name. In particular, when there is a `date` AND a `month` column in the same table, then it is confusing.

**Comment by JiaZhang42** [comment]
As a reader, I was confused by it for 1 second but quickly made sense of it. `month` would remind me it's actually a `ym` in the format of `ymd`. If it's changed to `date`, it would be more confusing as one doesn't know `2024-07-01` corresponds to data in June or July.

**Comment by christophscheuch** [comment]
We have come to a decision for the R `tidyfinance` package and should also implement the date for the books. See also the new vignette: https://cran.r-project.org/web/packages/tidyfinance/vignettes/dates-in-tidyfinance.html
