### ISSUE TITLE
Add affiliate link for TFWP

### ISSUE THREAD

**Issue by christophscheuch** [tidy-finance/website#123]
https://www.kqzyfj.com/click-101217142-14339043?url=https%3A%2F%2Fwww.routledge.com%2FTidy-Finance-with-Python%2FScheuch-Voigt-Weiss-Frey%2Fp%2Fbook%2F9781032676418

**Comment by patrick-weiss** [comment]
0058a44a3bc9857bfff1f0aab2257db462810b2c Does this already. Or do you want to add more? 

I thought about changing the callout note. Do you think that needs an update?
