### ISSUE TITLE
Improve documentation of CRSP v2 with respect to delisting returns

### ISSUE THREAD

**Issue by jestover** [tidy-finance/website#124]
I believe that you used to include delisting returns for CRSP, however, I noticed that now on the website it says, "As of July 2022, there is no need to additionally download delisting information since it is already contained in the most recent version of `msf`", with a similar statement about the daily security file.  

I tried to verify this in either the WRDS documentation or CRSP documentation but didn't see anything, and checking a couple of PERMNOs it didn't look like last day returns matched delisting returns.  Are you sure this is correct?  If so, it might be helpful to provide a source.

Thanks

**Comment by jestover** [comment]
Just as a follow up, I noticed afterwards that you are using msf_v2 and dsf_v2.  I used the original files in the spot check, so that might explain the differences I saw.  I have reached out to WRDS for clarification and will pass along their response.

**Comment by christophscheuch** [comment]
We have described the transition to CRSP 2.0 in this blog post: https://www.tidy-finance.org/blog/crsp-v2-update/#can-we-keep-using-the-old-crsp-data. I think @patrick-weiss can point you to the information that WRDS has provided in this regard. 

Maybe we link the blog post in the book and add a link to the specific WRDS information to the post?

**Comment by jestover** [comment]
Thanks!  I think that a link to the blog post would be very helpful.

Also, I heard back from WRDS and they pointed me to the following two resources...

[SIZ to CIZ Overview](https://wrds-www.wharton.upenn.edu/pages/support/manuals-and-overviews/crsp/stocks-and-indices/crsp-stock-and-indexes-version-2/crsp-ciz-overview/)
[SIZ to CIZ FAQ](https://wrds-www.wharton.upenn.edu/pages/support/manuals-and-overviews/crsp/stocks-and-indices/crsp-stock-and-indexes-version-2/crsp-ciz-faq/)

For completeness, and those who don't have access to WRDS, here is a resources on the CRSP website.

[CRSP METADATA GUIDE - STOCK & INDEXES FLAT FILE FORMAT 2.0 (CIZ)](https://www.crsp.org/wp-content/uploads/guides/CRSP_Metadata_Guide_Flat_File_Format_2.0.pdf)

I wasn't familiar with the "SIZ" or "CIZ", which I think Is part of why I was having trouble digging up the info.
