### ISSUE TITLE
Update ccmxpf_linktable to ccmxpf_lnkhist

### ISSUE THREAD

**Issue by giusmatera** [tidy-finance/website#138]
On the webpage describing the initial CRSP and Compustat data, the code references crsp.ccmxpf_linktable for querying the linking table between the two datasets. However, it appears that this table no longer exists. According to the [WRDS documentation](https://wrds-www.wharton.upenn.edu/pages/support/manuals-and-overviews/crsp/crspcompustat-merged-ccm/wrds-overview-crspcompustat-merged-ccm/), the correct reference should be either CCMXPF_LNKHIST or CCMXPF_LNKUSED.

Thank you for your great work!

Best,
Giuseppe

**Comment by patrick-weiss** [comment]
Thanks for the comment.

`crsp.ccmxpf_linktable` exists and works fine as of October 11, 2024.

In fact, running a comparison between `crsp.ccmxpf_linktable` and `crsp.ccmxpf_lnkhist` (taking a moment to admire the great name they picked) shows that they are the same.

`ccmxpf_lnkhist <- tbl(wrds, I("crsp.ccmxpf_lnkhist")) |>
  filter(linktype %in% c("LU", "LC") &
  linkprim %in% c("P", "C")) |>
  select(permno = lpermno, gvkey, linkdt, linkenddt) |>
  collect() |>
  mutate(linkenddt = replace_na(linkenddt, today())) |>
  arrange(permno, linkdt)`

`
ccmxpf_linktable <- tbl(wrds, I("crsp.ccmxpf_linktable")) |>
  filter(linktype %in% c("LU", "LC") &
    linkprim %in% c("P", "C") &
    usedflag == 1) |>
  select(permno = lpermno, gvkey, linkdt, linkenddt) |>
  collect() |>
  mutate(linkenddt = replace_na(linkenddt, today()))
`

Then, `all(ccmxpf_linktable == ccmxpf_lnkhist)` is TRUE.

**Comment by christophscheuch** [comment]
If the outrageously named ccmxpf_lnkhist is the official way forward, then we should go with it. I fear that ccmxpf_linktable might vanish without warning at some point.
