### ISSUE TITLE
SSL Error on Loading DOW Jones Constituents from ssga.com

### ISSUE THREAD

**Issue by lrwilke** [tidy-finance/website#139]
**Problem:**

In [python/introduction-to-tidy-finance.qmd](https://github.com/tidy-finance/website/blob/3d29b0861709745683639e36a8d76687dc86f53e/python/introduction-to-tidy-finance.qmd#L170), executing the code to load a DataFrame from the external website's Excel file throws an SSLCertificateError.

**Environment:**

MacOS Sonoma 14.4.1
Python 3.11.6

**Solution:**

Able to bypass the error by executing:

```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by christophscheuch** [comment]
Thank you for raising this point! Seems like the behavior of pandas or some other library changed here. I'll fix it right away.
