### ISSUE TITLE
Automatically Create Data Directory for SQLite File

### ISSUE THREAD

**Issue by lrwilke** [tidy-finance/website#142]
The current code in [Accessing and Managing Financial Data](https://www.tidy-finance.org/python/accessing-and-managing-financial-data.html) assumes in the section "Setting up a Database" that the `data` directory already exists.
When running the command `tidy_finance = sqlite3.connect(database="data/tidy_finance_python.sqlite")` without previously creating the `data` directory, SQLite will throw an `OperationalError: unable to open database file`.

This can be avoided by explicitly checking whether the directory exists and creating it if it doesn't:

```python
# Define the path to the database
database_path = "data/tidy_finance_python.sqlite"
directory = os.path.dirname(database_path)

# Create the directory if it doesn't exist
if not os.path.exists(directory):
    os.makedirs(directory)
```

Alternatively of course, you could just mention in the text that the `data`-directory has to be created beforehands.

If I missed that part - sorry and please disregard this issue! :)

**Comment by christophscheuch** [comment]
Great suggestion, thank you! We definitely missed this and will update the text accordingly :)
