### ISSUE TITLE
Error in connecting to tidyfinance

### ISSUE THREAD

**Issue by tidyfinanceR** [tidy-finance/website#32]
> tidy_finance <- dbConnect(
+   SQLite(), "data/tidy_finance.sqlite",
+   extended_types = TRUE
+ )

Error: Could not connect to database:
unable to open database file

**Comment by voigtstefan** [comment]
Hi @tidyfinanceR. Can you elaborate more on what you the problem is? Do you have the file tidy_finance.sqplite locally im the folder data?

**Comment by tidyfinanceR** [comment]
Hi Stefan,

Thanks for your reply. I am not sure what you mean.

Here is what I am trying to do (running in the latest version of R on
updated MacOS):
1. Parametric Portfolio Policies
<https://www.tidy-finance.org/parametric-portfolio-policies.html#:~:text=library(RSQLite)-,Data%20Preparation,data%20from%20our%20SQLite%2Ddatabase%20introduced%20in%20Chapters%202%2D4.,-tidy_finance%20%3C%2D%20dbConnect>

I am running the code as follows:

"library(tidyverse)
library(RSQLite)
tidy_finance <- dbConnect(
  SQLite(), "data/tidy_finance.sqlite",
  extended_types = TRUE
)"

This gives an error that the database could not be found. I am unsure what
I am doing wrong, or I should be doing something different. Perhaps you
could help me out?

Best,
Taimur


On Wed, Apr 26, 2023 at 10:48 PM Stefan Voigt ***@***.***>
wrote:

> Hi @tidyfinanceR
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tidyfinanceR&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Koog9hnZCLYxDh6OGC1HyQ&m=gbPsX5anaXe7pvayoqy5pEA8li6p2h7gqrI1QoYgPbhKVC5SDVwJFyCFiMHU76uQ&s=XOHk-zAccsC_UUcfGJaxMU1Abjo-664fPZZBNjS3UFM&e=>.
> Can you elaborate more on what you the problem is? Do you have the file
> tidy_finance.sqplite locally im the folder data?
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tidy-2Dfinance_website_issues_32-23issuecomment-2D1523889445&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Koog9hnZCLYxDh6OGC1HyQ&m=gbPsX5anaXe7pvayoqy5pEA8li6p2h7gqrI1QoYgPbhKVC5SDVwJFyCFiMHU76uQ&s=yJu760gKEdimqUnFWr1sxOysh5pgC2x1-rgQ9gWf0EE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A7OJP4Y6OTINMTY2IEZ73NDXDFUXBANCNFSM6AAAAAAXMVA4UI&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=Koog9hnZCLYxDh6OGC1HyQ&m=gbPsX5anaXe7pvayoqy5pEA8li6p2h7gqrI1QoYgPbhKVC5SDVwJFyCFiMHU76uQ&s=VtKyeXvmS-r80EEL3lwQ0G9Qn8rf2TvQh9FXpjYHB34&e=>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 

Syed T*aimur Hasan*

BA Economics, NYU Class of 2023



Linkedin: Taimur Hasan <https://www.linkedin.com/in/taimur-hasan/>

Mobile (UAE): +971 50 143 5047

**Comment by voigtstefan** [comment]
Hi Taimur,
Thanks for the clarification. In order to run the code you need to the data as a file which we generate in chapters 2-4. Go through these chapters (if you have WRDS access) and you'll have created the file. If you have other access to CRSP data, you can replace this chunk with our way of managing financial data, of course.
