### ISSUE TITLE
FamaMacBeth Exercise 3.

### ISSUE THREAD

**Issue by datrickf** [tidy-finance/website#44]
I feel like exercise 3. in the Fama-MacBeth chapter would benefit from a little more explaining. Maybe it would make sense to mention in the chapter that one can use the characteristics or a factor exposures derived from time series regressions as input for the cross-sectional regressions to clearly where one would use the rolling windows regressions.

**Comment by patrick-weiss** [comment]
We just removed exercise 3 from the chapter (see Commit 2d558389d400ff9056d6fe5a81b5218276ed4d6e). Rolling-window regressions are now the standard in beta estimation and this exercise is no longer relevant.
