### ISSUE TITLE
Speed up preparing daily CRSP data

### ISSUE THREAD

**Issue by McXD** [tidy-finance/website#73]
I'm following [this guide](https://www.tidy-finance.org/r/wrds-crsp-and-compustat.html#daily-crsp-data) to download and prepare daily crsp data. And I think there is room for improvement.

The 'big data' issue indeed exists and spliting the data is a good solution. However, the  _chunk_ size should be a tunable parameter, depending on how much RAM is available. A bigger `chunk_size` means more parallel processing but higher memory consumption.

I'm only downloading data from 1996 to 2020. The current code in the book only download and process *1* (`chunk_size = 1`)PERMNO at a time. The esimated time is about **4 hours** (by the `progress` package). However, if I process *100* (`chunk_size = 100`) at a time, this will only take about **50 minutes**.

Below is my modifed code

```r
dsf_db <- tbl(wrds, in_schema("crsp", "dsf"))

factors_ff3_daily <- tbl(db, "factors_ff3_daily") |>
  collect()

permnos <- tbl(db, "crsp_monthly") |>
  distinct(permno) |>
  pull()

# Determine the number of chunks
chunk_size <- 100
num_chunks <- ceiling(length(permnos) / chunk_size)

# Progress bar using progress package
pb <- progress_bar$new(
  format = "[:bar] :percent eta: :eta",
  total = num_chunks
)

for (j in 1:num_chunks) {
  # Select the permnos for this chunk
  permno_chunk <- permnos[((j - 1) * chunk_size + 1):min(j * chunk_size, length(permnos))]

  # Process all permnos in the chunk at once
  crsp_daily_sub <- dsf_db |>
    filter(permno %in% permno_chunk &
      date >= start_date & date <= end_date) |>
    select(permno, date, ret) |>
    collect() |>
    drop_na()

  if (nrow(crsp_daily_sub) > 0) {
    crsp_daily_sub <- crsp_daily_sub |>
      mutate(month = floor_date(date, "month")) |>
      left_join(factors_ff3_daily |>
        select(date, rf), by = "date") |>
      mutate(
        ret_excess = ret - rf,
        ret_excess = pmax(ret_excess, -1)
      ) |>
      select(permno, date, month, ret, ret_excess)

    dbWriteTable(db,
      "crsp_daily",
      value = crsp_daily_sub,
      overwrite = ifelse(j == 1, TRUE, FALSE),
      append = ifelse(j != 1, TRUE, FALSE)
    )
  }

  pb$tick()
}
```

**Comment by christophscheuch** [comment]
Great suggestion, thank you! I'll definitely implement this approach in both R and Python :)

**Comment by McXD** [comment]
It turns out there was a bug in the code (I forgot to change `10` to `chunk_size` during `permnos` selection). So I actually downloaded only 1/10 of the data. But there's still speed improvement (by a factor of 4-6) 😬

Another way is to chunk the data by `date` to avoid comparing `PERMNO` when reading the database. So it should be faster. But this will introduce some unwanted stocks.
