### ISSUE TITLE
Fama-Macbeth Regression

### ISSUE THREAD

**Issue by mandarpriya** [tidy-finance/website#81]
Sir,
In this part of code risk_premiums <- data_fama_macbeth |>
  nest(data = c(ret_excess_lead, beta, log_mktcap, bm, permno)) |>
  mutate(estimates = map(
    data,
    ~ tidy(lm(ret_excess_lead ~ beta + log_mktcap + bm, data = .x))
  )) |>
  unnest(estimates)

 i see that the result obtained are general. We dont get the results for each id or permno.  So if for each permno we need then what modifications are needed?

**Comment by voigtstefan** [comment]
Should you be interested in computing time-series regressions per permno you likely want to assign permno as a grouping variable. Without having tested the code, it seems like 

` risk_premiums <- data_fama_macbeth |>
nest(data = c(ret_excess_lead, beta, log_mktcap, bm, month)) |>
mutate(estimates = map(
data,
~ tidy(lm(ret_excess_lead ~ beta + log_mktcap + bm, data = .x))
)) |>
unnest(estimates)`

may do the job such that you receive a time-series regression for each permno. However, note that the result is not related to Fama-Macbeth regressions anymore but only yields per firm exposure of future excess returns to the different stock characteristics. 

I do not see a direct to-do for the codebase of tidy finance and thus close the issue.
