### ISSUE TITLE
Figure 2 (Optimal allocation for different strategies) omits weights for reg-t constraints

### ISSUE THREAD

**Issue by voigtstefan** [tidy-finance/website#83]
Not evaluated the code in detail yet but I see that the input to the figure is

```
tibble(
  `No short-sale` = w_no_short_sale$solution,
  `Minimum Variance` = w_mvp,
  `Efficient portfolio` = compute_efficient_weight(Sigma, mu),
  `Regulation-T` = w_reg_t$par,
  Industry = colnames(industry_returns)
)
 ```

At the same time, the resulting figure omits the "Regulation-T" column.

**Comment by christophscheuch** [comment]
Fixed in https://github.com/tidy-finance/website/commit/ed49508587c7a0e9cb85fb76f813f5d2fd9cd7ba
